apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipping-consumer
  template:
    metadata:
      labels:
        app: shipping-consumer
    spec:
      containers:
        - name: consumer
          image: shipping-consumer:latest
          command: ["python", "consumer_shipping.py"]
